/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.*;
/**
 *
 * @author rafin
 */
public class CadastroClienteform extends javax.swing.JDialog {
    private MeusClientes meusClientes;
    private Cliente clienteNovo;
    /**
     * Creates new form CadastroClienteform
     */
    public CadastroClienteform(java.awt.Frame parent, boolean modal, MeusClientes meusClientes) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        this.meusClientes = meusClientes;
        this.clienteNovo = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelcpf = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtCPF = new javax.swing.JTextField();
        jTxtemail = new javax.swing.JTextField();
        jLabelkigaucho = new javax.swing.JLabel();
        jButtonSalvarcadastro = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(242, 242, 242));
        jLabelNome.setText("Nome:");
        add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 30));

        jLabelcpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelcpf.setForeground(new java.awt.Color(242, 242, 242));
        jLabelcpf.setText("CPF:");
        add(jLabelcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 60, 20));

        jLabelemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelemail.setForeground(new java.awt.Color(242, 242, 242));
        jLabelemail.setText("E-mail:");
        add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jTxtNome.setText("ex: \"reinaldo\"");
        add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jTxtCPF.setText("ex: 111.111.111-11");
        add(jTxtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jTxtemail.setText("ex: aleatorio@gmail.com");
        add(jTxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabelkigaucho.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabelkigaucho.setForeground(new java.awt.Color(255, 51, 51));
        jLabelkigaucho.setText("RESTAURANTE KIGAÚCHO");
        add(jLabelkigaucho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jButtonSalvarcadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSalvarcadastro.setText("Salvar cadastro");
        jButtonSalvarcadastro.addActionListener(this::jButtonSalvarcadastroActionPerformed);
        add(jButtonSalvarcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    public Cliente getClienteNovo(){
        return this.clienteNovo;
    }
    private void jButtonSalvarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarcadastroActionPerformed
        String nome = jTxtNome.getText().trim();
        String cpf = jTxtCPF.getText().trim();
        String email = jTxtemail.getText().trim();
        
        if (nome.isEmpty() || cpf.isEmpty() || email.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return;
        }
        this.clienteNovo = new Cliente(nome, cpf, email, meusClientes);
        this.dispose();
    }//GEN-LAST:event_jButtonSalvarcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroClienteform dialog = new CadastroClienteform(new java.awt.Frame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarcadastro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelkigaucho;
    private javax.swing.JTextField jTxtCPF;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtemail;
    // End of variables declaration//GEN-END:variables
}
