package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.Tablet;
import com.mycompany.sstema.restaurante.Bebida;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */


/**
 *
 * @author rafin
 */
public class CadastroBebida extends javax.swing.JDialog {
    private String nome;
    private float preco;
    private Tablet tablet;
    /**
     * Creates new form CadastroBebida
     */
    public CadastroBebida(java.awt.Frame parent, boolean modal,String nome, float preco, Tablet tablet) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        this.nome = nome;
        this.preco = preco;
        this.tablet = tablet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        btnCadastrarBebida = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("RESTAURANTE KIGAÚCHO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        labelFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFornecedor.setForeground(new java.awt.Color(242, 242, 242));
        labelFornecedor.setText("Fornecedor:");
        add(labelFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 60));
        add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 140, -1));

        btnCadastrarBebida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrarBebida.setText("Cadastrar bebida");
        btnCadastrarBebida.addActionListener(this::btnCadastrarBebidaActionPerformed);
        add(btnCadastrarBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCadastrarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarBebidaActionPerformed
        String fornecedor = txtFornecedor.getText();
        Bebida bebidaNova = new Bebida(fornecedor, preco, nome);
        tablet.addProduto(bebidaNova);
        JOptionPane.showMessageDialog(this, "Comida cadastrada com sucesso!");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCadastrarBebidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroBebida dialog = new CadastroBebida(new java.awt.Frame(), true,"Produto padrão",0.0f,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JTextField txtFornecedor;
    // End of variables declaration//GEN-END:variables
}
