package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.Tablet;
import com.mycompany.sstema.restaurante.ItemCardapio;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */


/**
 *
 * @author rafin
 */
public class CadastroProduto extends javax.swing.JDialog {
    private ItemCardapio item;
    private Tablet tablet;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto(java.awt.Frame parent, boolean modal, Tablet tablet) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        this.tablet = tablet;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelkigaucho = new javax.swing.JLabel();
        jLabelnomeproduto = new javax.swing.JLabel();
        jLabelprecoproduto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnavancar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelkigaucho.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabelkigaucho.setForeground(new java.awt.Color(255, 51, 51));
        jLabelkigaucho.setText("RESTAURANTE KIGAÚCHO");
        getContentPane().add(jLabelkigaucho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelnomeproduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelnomeproduto.setForeground(new java.awt.Color(242, 242, 242));
        jLabelnomeproduto.setText("Nome:");
        getContentPane().add(jLabelnomeproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabelprecoproduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelprecoproduto.setForeground(new java.awt.Color(242, 242, 242));
        jLabelprecoproduto.setText("Preço:");
        getContentPane().add(jLabelprecoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        txtNome.setText("Digite o nome");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        txtPreco.setText("Digite o preço");
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 30));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Comida", " " }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 192, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Tipo de produto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 185, 150, 40));

        btnavancar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnavancar.setText("Avançar");
        btnavancar.addActionListener(this::btnavancarActionPerformed);
        getContentPane().add(btnavancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnavancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavancarActionPerformed
        String nome = txtNome.getText();
        float preco = Float.parseFloat(txtPreco.getText());
        String tipo = cbTipo.getSelectedItem().toString();
        this.dispose();
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (window instanceof java.awt.Frame) ? (java.awt.Frame) window : new java.awt.Frame();
        if (tipo.equals("Comida")){
            CadastroComida telaComida = new CadastroComida(parentFrame,true,nome,preco,this.tablet);
            telaComida.setLocationRelativeTo(null);
            telaComida.setVisible(true);
        } else {
            CadastroBebida telaBebida = new CadastroBebida(parentFrame,true,nome,preco,this.tablet);
            telaBebida.setLocationRelativeTo(null);
            telaBebida.setVisible(true);
            
        }
    }//GEN-LAST:event_btnavancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroProduto dialog = new CadastroProduto(new java.awt.Frame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnavancar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelkigaucho;
    private javax.swing.JLabel jLabelnomeproduto;
    private javax.swing.JLabel jLabelprecoproduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
