package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.Tablet;
import com.mycompany.sstema.restaurante.Comida;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */


/**
 *
 * @author rafin
 */
public class CadastroComida extends javax.swing.JDialog {
    private String nome;
    private float preco;
    private Tablet tablet;
    /**
     * Creates new form CadastroComida
     */
    public CadastroComida(java.awt.Frame parent, boolean modal, String nome, float preco, Tablet tablet) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        this.nome = nome;
        this.preco = preco;
        this.tablet = tablet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        jLabelIngredientes = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredientes = new javax.swing.JTextArea();
        btnCadastrarComida = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("RESTAURANTE KIGAÚCHO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(242, 242, 242));
        labelDescricao.setText("Descrição:");
        add(labelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabelIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIngredientes.setForeground(new java.awt.Color(242, 242, 242));
        jLabelIngredientes.setText("Ingredientes:");
        add(jLabelIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        txtDescricao.setText("Digite a descrição da comida");
        add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 30));

        txtIngredientes.setColumns(20);
        txtIngredientes.setLineWrap(true);
        txtIngredientes.setRows(5);
        txtIngredientes.setText("Digite os ingredientes da comida");
        txtIngredientes.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtIngredientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 220, 90));

        btnCadastrarComida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrarComida.setText("Cadastar Comida");
        btnCadastrarComida.addActionListener(this::btnCadastrarComidaActionPerformed);
        add(btnCadastrarComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCadastrarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarComidaActionPerformed
        String descricao = txtDescricao.getText();
        ArrayList<String> ingredientes = new ArrayList<>();
        String[] linhas = txtIngredientes.getText().split("\n");
        
        for (String linha : linhas){
            if (!linha.trim().isEmpty()){
                ingredientes.add(linha.trim());
            }
        }
        Comida novaComida = new Comida(descricao,nome,preco);
        novaComida.setIngredientes(ingredientes);
        this.tablet.addProduto(novaComida);
        JOptionPane.showMessageDialog(this, "Comida cadastrada com sucesso!");
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_btnCadastrarComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroComida dialog = new CadastroComida(new java.awt.Frame(),true,"Produto padrâo", 0.0f,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIngredientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextArea txtIngredientes;
    // End of variables declaration//GEN-END:variables
}
