/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.*;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author rafin
 */
public class CadastroClienteform extends javax.swing.JDialog {
    private MeusClientes meusClientes;
    private Cliente clienteNovo;
    /**
     * Creates new form CadastroClienteform
     */
    public CadastroClienteform(java.awt.Frame parent, boolean modal, MeusClientes meusClientes) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.WHITE);
        ImageIcon icon = new ImageIcon("C:/Users/rafin/Downloads/Logo Ki Gaúcho_page-0001.jpg");

        Image imagem = icon.getImage().getScaledInstance(
        250,
        250,
        Image.SCALE_SMOOTH);

        lblLogo.setIcon(new ImageIcon(imagem));
        this.meusClientes = meusClientes;
        this.clienteNovo = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelcpf = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtCPF = new javax.swing.JTextField();
        jTxtemail = new javax.swing.JTextField();
        jButtonSalvarcadastro = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 60, 30));

        jLabelcpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelcpf.setText("CPF:");
        getContentPane().add(jLabelcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, 20));

        jLabelemail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelemail.setText("E-mail:");
        getContentPane().add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jTxtNome.setBackground(new java.awt.Color(204, 204, 204));
        jTxtNome.addActionListener(this::jTxtNomeActionPerformed);
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 210, -1));

        jTxtCPF.setBackground(new java.awt.Color(204, 204, 204));
        jTxtCPF.addActionListener(this::jTxtCPFActionPerformed);
        getContentPane().add(jTxtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 210, -1));

        jTxtemail.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 210, -1));

        jButtonSalvarcadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSalvarcadastro.setText("Registrar");
        jButtonSalvarcadastro.addActionListener(this::jButtonSalvarcadastroActionPerformed);
        getContentPane().add(jButtonSalvarcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Cadastro do Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    public Cliente getClienteNovo(){
        return this.clienteNovo;
    }
    private void jButtonSalvarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarcadastroActionPerformed
        String nome = jTxtNome.getText().trim();
        String cpf = jTxtCPF.getText().trim();
        String email = jTxtemail.getText().trim();
        
        if (nome.isEmpty() || cpf.isEmpty() || email.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return;
        }
        this.clienteNovo = new Cliente(nome, cpf, email);
        meusClientes.addCliente(clienteNovo);
        this.dispose();
    }//GEN-LAST:event_jButtonSalvarcadastroActionPerformed

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jTxtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroClienteform dialog = new CadastroClienteform(new java.awt.Frame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarcadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JTextField jTxtCPF;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtemail;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
