package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.MeusClientes;
import com.mycompany.sstema.restaurante.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */


/**
 *
 * @author rafin
 */
public class Loginform extends javax.swing.JDialog {
    private MeusClientes meusClientes;
    private Cliente clienteAtual;
    /**
     * Creates new form Loginform
     */
    public Loginform(java.awt.Frame parent, boolean modal, MeusClientes meusClientes, Cliente clienteAtual) {
        super(parent, modal);
        initComponents();
        this.meusClientes = meusClientes;
        this.clienteAtual = clienteAtual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKigaucho = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKigaucho.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        labelKigaucho.setForeground(new java.awt.Color(255, 51, 51));
        labelKigaucho.setText("RESTAURANTE KIGAÚCHO");
        add(labelKigaucho, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        labelCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCpf.setText("CPF:");
        add(labelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        txtCpf.setText("Digite o seu cpf");
        add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 140, 30));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setText("Fazer login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    public Cliente getClienteAtual(){
        return this.clienteAtual;
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String cpf = txtCpf.getText();
        
        this.clienteAtual = this.meusClientes.encontrarCliente(cpf);
        if (this.clienteAtual == null)
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente não encontrado!","Erro de Login",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,"Login realizado com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Loginform dialog = new Loginform(new java.awt.Frame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelKigaucho;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
