package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.Cliente;
import com.mycompany.sstema.restaurante.Mesa;
import com.mycompany.sstema.restaurante.MinhasMesas;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author rafin
 */
public class TelaCliente extends javax.swing.JFrame {
    private Cliente clienteAtual;
    private MinhasMesas minhasMesas;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCliente.class.getName());

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente(Cliente cliente, MinhasMesas minhasMesas) {
        initComponents();
        this.clienteAtual = cliente;
        this.minhasMesas = minhasMesas;
        
        lblNome.setText(clienteAtual.getNome());
        lblCpf.setText(clienteAtual.getCPF());
        lblBonus.setText("R$ " + cliente.getBonus());
        lblEmail.setText(clienteAtual.getEmail());
        if (clienteAtual.getMesa() != null)
            lblMesa.setText("" + clienteAtual.getMesa().getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelMesa = new javax.swing.JLabel();
        jLabelBonus = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNovoPedido = new javax.swing.JButton();
        btnRemoverPedido = new javax.swing.JButton();
        btnFecharConta = new javax.swing.JButton();
        btnEscolherMesa = new javax.swing.JButton();
        btnClientesdaMesa = new javax.swing.JButton();
        LblPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("Área - Cliente");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCpf.setText("CPF:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("E-mail:");

        jLabelMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMesa.setText("Mesa:");

        jLabelBonus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBonus.setText("Bônus Acumulado:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblBonus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnNovoPedido.setText("Novo Pedido");

        btnRemoverPedido.setText("Remover Pedido");

        btnFecharConta.setText("Fechar Conta");

        btnEscolherMesa.setText("Escolher Mesa");
        btnEscolherMesa.addActionListener(this::btnEscolherMesaActionPerformed);

        btnClientesdaMesa.setText("Clientes da Mesa");

        LblPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblPedido.setText("Pedidos do Cliente");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Preço", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCpf)
                        .addGap(18, 18, 18)
                        .addComponent(lblCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(18, 18, 18)
                        .addComponent(lblNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelBonus)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBonus)
                        .addGap(178, 178, 178))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(317, 317, 317))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPedido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovoPedido)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoverPedido)
                                .addGap(26, 26, 26)
                                .addComponent(btnFecharConta)))
                        .addGap(27, 27, 27)
                        .addComponent(btnEscolherMesa)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesdaMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(lblNome))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCpf)
                            .addComponent(lblCpf))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(lblEmail)
                            .addComponent(lblBonus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMesa)
                            .addComponent(lblMesa)))
                    .addComponent(jLabelBonus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPedido)
                    .addComponent(btnRemoverPedido)
                    .addComponent(btnFecharConta)
                    .addComponent(btnEscolherMesa)
                    .addComponent(btnClientesdaMesa))
                .addGap(44, 44, 44)
                .addComponent(LblPedido)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherMesaActionPerformed
        TelaMesas telaMesa = new TelaMesas(minhasMesas);
        telaMesa.setLocationRelativeTo(this);
        telaMesa.setVisible(true);
    }//GEN-LAST:event_btnEscolherMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPedido;
    private javax.swing.JButton btnClientesdaMesa;
    private javax.swing.JButton btnEscolherMesa;
    private javax.swing.JButton btnFecharConta;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnRemoverPedido;
    private javax.swing.JLabel jLabelBonus;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
