/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sstema.restaurante.view.telaprincipal;
import com.mycompany.sstema.restaurante.*;

/**
 *
 * @author rafin
 */
public class telaprincipal extends javax.swing.JFrame {
    private MeusClientes meusClientes;
    private MinhasMesas minhasMesas;
    private Tablet tablet;
    private Cozinha cozinha;
    private Cliente clienteAtual;
    private Pedido pedidoAtual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaprincipal.class.getName());

    /**
     * Creates new form telaprincipal
     */
    public telaprincipal() {
        initComponents();
        // Troque 'Color.LIGHT_GRAY' pela cor que você quiser (ex: Color.WHITE, Color.BLACK, etc.)
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        this.meusClientes = new MeusClientes();
        this.cozinha = new Cozinha();
        this.tablet = new Tablet();
        this.minhasMesas = new MinhasMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelkigaucho = new javax.swing.JLabel();
        btnclickcliente = new javax.swing.JButton();
        btnclickproduto = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnCozinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        labelkigaucho.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        labelkigaucho.setForeground(new java.awt.Color(255, 51, 51));
        labelkigaucho.setText("RESTAURANTE KIGAÚCHO");

        btnclickcliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnclickcliente.setText("Cadastrar cliente");
        btnclickcliente.addActionListener(this::btnclickclienteActionPerformed);

        btnclickproduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnclickproduto.setText("Cadastrar produto");
        btnclickproduto.addActionListener(this::btnclickprodutoActionPerformed);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        btnCozinha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCozinha.setText("Visualizar Cozinha");
        btnCozinha.addActionListener(this::btnCozinhaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(labelkigaucho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnclickproduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclickcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(btnCozinha)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelkigaucho)
                .addGap(42, 42, 42)
                .addComponent(btnclickcliente)
                .addGap(18, 18, 18)
                .addComponent(btnclickproduto)
                .addGap(18, 18, 18)
                .addComponent(btnCozinha)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclickclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclickclienteActionPerformed
        CadastroClienteform telaCadastro = new CadastroClienteform(this,true,this.meusClientes);
        telaCadastro.setLocationRelativeTo(this);
        telaCadastro.setVisible(true);
        this.clienteAtual = telaCadastro.getClienteNovo();
        if (this.clienteAtual != null){
            // Certifique-se de que existem os DOIS parâmetros separados por vírgula:
// Parâmetro 1: parentComponent (this)
// Parâmetro 2: A mensagem de texto
javax.swing.JOptionPane.showMessageDialog(this, "Tela Principal recebeu o cliente ativo: " + (this.clienteAtual.fecharConta() == 0 ? "Pronto para fazer pedidos" : "Conta pendente"));
        }
        
    
    }//GEN-LAST:event_btnclickclienteActionPerformed

    private void btnclickprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclickprodutoActionPerformed
        CadastroProduto telaBase = new CadastroProduto(this,true, this.tablet);
        telaBase.setLocationRelativeTo(this);
        telaBase.setVisible(true);
    }//GEN-LAST:event_btnclickprodutoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         Loginform telaLogin = new Loginform(this,true,this.meusClientes,this.clienteAtual, minhasMesas,tablet,cozinha);
        telaLogin.setLocationRelativeTo(this);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCozinhaActionPerformed
        TelaCozinha telaCozinha = new TelaCozinha(this.cozinha);
        telaCozinha.setLocationRelativeTo(this);
        telaCozinha.setVisible(true);
    }//GEN-LAST:event_btnCozinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaprincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCozinha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnclickcliente;
    private javax.swing.JButton btnclickproduto;
    private javax.swing.JLabel labelkigaucho;
    // End of variables declaration//GEN-END:variables
}

